github:
  owner: "UPDATECLI_GITHUB_OWNER"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "main"
  author: "Kubewarden bot"
  email: "cncf-kubewarden-maintainers@lists.cncf.io"
  user: "UPDATECLI_GITHUB_OWNER"
